<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>PixelPro2.PcMonitorPlugin</AssemblyName>
    <Version>2.5.0</Version>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../PixelPro2/SystemMonitor.cs" Link="SystemMonitor.cs" />
    <Compile Include="../PixelPro2/PluginProtocol.cs" Link="PluginProtocol.cs" />
    <PackageReference Include="LibreHardwareMonitorLib" Version="0.9.6" />
  </ItemGroup>
</Project>
